---
AWSTemplateFormatVersion: 2010-09-09
Description: A service for Transit Gateway VPN management.
Parameters:
    S3BucketName:
        Type: String
        AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
        ConstraintDescription: >-
            Deployment resource S3 bucket name can include numbers, lowercase letters,
            uppercase letters, and hyphens (-). It cannot start or end with a hyphen
            (-).
        Description: >-
            S3 bucket name for the Deployment package. Bucket name can include
            numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot
            start or end with a hyphen (-).
    S3KeyPrefix:
        Type: String
        AllowedPattern: '^[0-9a-zA-Z-/]*$'
        ConstraintDescription: >-
            Deployment package S3 key prefix can include numbers, lowercase letters,
            uppercase letters, hyphens (-), and forward slash (/).
        Description: >-
            S3 key prefix for the deployment package. Key prefix can include numbers,
            lowercase letters, uppercase letters, hyphens (-), and forward slash (/).
    ResourceTagPrefix:
        Type: String
        AllowedPattern: '[0-9a-zA-Z@.#-]+'
        MaxLength: 64
        ConstraintDescription: >-
            Resource tag prefix can include numbers, lowercase letters, uppercase
            letters, ampersat(@) , hyphens (-), period (.), and hash (#). Max length
            is 64.
        Description: >-
            A prefix for tag key ResourceGroup on all resources. It's also used as the
            name prefix of all applicable resources. Can only contain numbers,
            lowercase letters, uppercase letters, ampersat(@) , hyphens (-), period
            (.), and hash (#). Max length is 64.
    CustomIdentifier:
        Type: String
        MaxLength: '10'
        AllowedPattern: '[A-Za-z0-9]+'
        ConstraintDescription: must only contain uppercase and lowercase letters and numbers
        Description: >-
            An alternative name prefix. This shorter version of prefix is used on a
            resource that Resource tag prefix cannot apply to. Must be at most 10
            characters long and only contain uppercase, lowercase letters, and
            numbers. Max length is 10.
    UniqueId:
        Type: String
        MaxLength: '8'
        AllowedPattern: '[A-Za-z0-9]+'
        ConstraintDescription: must only contain uppercase and lowercase letters and digits
        Description: >-
            A random text suffix for the DynamoDB table name which can help ensure the
            DB table name is unique per region. Can only contain uppercase, lowercase
            letters, and digits. Max length is 8.
    CustomAssetContainer:
        Type: String
        Default: ''
        Description: >-
            The name of the S3 bucket which contains your custom assets. Required if
            'use custom asset location' is set to 'yes'.
    CustomAssetDirectory:
        Type: String
        Default: ''
        Description: >-
            The sub path within the 'custom asset container' which serves as the top
            level directory of all your custom assets. If 'use custom asset location'
            is set to 'yes', and this value is left empty, the 'custom asset
            container' will serve as the top level directory.
Conditions:
    GovCloudCondition: !Equals
        - !Ref 'AWS::Region'
        - us-gov-west-1
    IfUseCustomAssetContainer: !Not
        - !Equals
          - !Ref CustomAssetContainer
          - ''
Resources:
    StackCopyLambdaSource:
        Type: 'AWS::CloudFormation::Stack'
        Properties:
            Parameters:
                S3BucketName: !Ref S3BucketName
                S3KeyPrefix: !Ref S3KeyPrefix
                ObjectPaths: functions/packages/fgt-as-handler.zip
            TemplateURL: !Sub
                - >-
                    https://${S3BucketName}.${S3Region}.amazonaws.com/${S3KeyPrefix}templates/copy-objects.template.yaml
                - S3Region: !If
                      - GovCloudCondition
                      - s3-us-gov-west-1
                      - s3
                  S3BucketName: !Ref S3BucketName
                  S3KeyPrefix: !Ref S3KeyPrefix
            TimeoutInMinutes: '5'
    TransitGatewayVpnHandler:
        Type: 'AWS::Lambda::Function'
        Properties:
            Description: A service for Transit Gateway VPN management.
            FunctionName: !Join
                - '-'
                - - !Ref CustomIdentifier
                  - !Ref UniqueId
                  - fortigate-transit-gateway-vpn-handler
            Runtime: nodejs12.x
            Role: !GetAtt
                - IamRoleTransitGatewayVpnHandler
                - Arn
            Handler: index.tgwLambdaPeerInvocationHandler
            Timeout: 600
            Code:
                S3Bucket: !GetAtt
                    - StackCopyLambdaSource
                    - Outputs.DestinationBucket
                S3Key: !Sub
                    - '${KeyPrefix}functions/packages/fgt-as-handler.zip'
                    - KeyPrefix: !GetAtt
                          - StackCopyLambdaSource
                          - Outputs.KeyPrefix
            Environment:
                Variables:
                    RESOURCE_TAG_PREFIX: !Ref ResourceTagPrefix
            Tags:
                - Key: ResourceGroup
                  Value: !Ref ResourceTagPrefix
        DependsOn:
            - StackCopyLambdaSource
    IamRoleTransitGatewayVpnHandler:
        Type: 'AWS::IAM::Role'
        Properties:
            ManagedPolicyArns:
                - 'arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess'
                - 'arn:aws:iam::aws:policy/AWSLambdaExecute'
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - lambda.amazonaws.com
                      Action:
                          - 'sts:AssumeRole'
            Path: /
            Policies:
                - PolicyName: tgw-vpn-handler-policy
                  PolicyDocument:
                      Version: 2012-10-17
                      Statement:
                          - Effect: Allow
                            Action:
                                - 'dynamodb:CreateTable'
                                - 'dynamodb:DescribeTable'
                                - 'dynamodb:Scan'
                                - 'dynamodb:Query'
                                - 'dynamodb:DeleteItem'
                                - 'dynamodb:GetItem'
                                - 'dynamodb:PutItem'
                                - 'dynamodb:UpdateItem'
                            Resource: !Sub
                                - >-
                                    arn:aws:dynamodb:${AWS_REGION}:${AWS_ACCOUNT_ID}:table/${RESOURCE_PREFIX}*
                                - AWS_REGION: !Ref 'AWS::Region'
                                  AWS_ACCOUNT_ID: !Ref 'AWS::AccountId'
                                  RESOURCE_PREFIX: !Ref ResourceTagPrefix
                          - Effect: Allow
                            Action:
                                - 'autoscaling:CompleteLifecycleAction'
                                - 'autoscaling:SetDesiredCapacity'
                                - 'autoscaling:SetInstanceProtection'
                                - 'autoscaling:ExitStandby'
                                - 'autoscaling:BatchPutScheduledUpdateGroupAction'
                                - 'autoscaling:EnterStandby'
                                - 'autoscaling:PutScheduledUpdateGroupAction'
                                - 'autoscaling:UpdateAutoScalingGroup'
                                - 'autoscaling:DeleteNotificationConfiguration'
                                - 'autoscaling:SetInstanceHealth'
                                - 'autoscaling:TerminateInstanceInAutoScalingGroup'
                                - 'autoscaling:AttachLoadBalancers'
                                - 'autoscaling:DetachLoadBalancers'
                                - 'autoscaling:BatchDeleteScheduledAction'
                                - 'autoscaling:ResumeProcesses'
                                - 'autoscaling:SetDesiredCapacity'
                                - 'autoscaling:PutLifecycleHook'
                                - 'autoscaling:DetachLoadBalancerTargetGroups'
                                - 'autoscaling:SuspendProcesses'
                                - 'autoscaling:AttachLoadBalancerTargetGroups'
                                - 'autoscaling:AttachInstances'
                                - 'autoscaling:CompleteLifecycleAction'
                                - 'autoscaling:CreateOrUpdateTags'
                                - 'autoscaling:SetInstanceProtection'
                                - 'autoscaling:DeleteAutoScalingGroup'
                                - 'autoscaling:DeleteLifecycleHook'
                                - 'autoscaling:CreateAutoScalingGroup'
                                - 'autoscaling:DeleteScheduledAction'
                                - 'autoscaling:DetachInstances'
                                - 'autoscaling:RecordLifecycleActionHeartbeat'
                            Resource: !Sub
                                - >-
                                    arn:aws:autoscaling:${AWS_REGION}:${AWS_ACCOUNT_ID}:autoScalingGroup:*:autoScalingGroupName/${RESOURCE_PREFIX}*
                                - AWS_REGION: !Ref 'AWS::Region'
                                  AWS_ACCOUNT_ID: !Ref 'AWS::AccountId'
                                  RESOURCE_PREFIX: !Ref ResourceTagPrefix
                          - Effect: Allow
                            Action:
                                - 'autoscaling:DescribeAutoScalingNotificationTypes'
                                - 'autoscaling:DescribeAutoScalingInstances'
                                - 'ec2:DescribeInstances'
                                - 'autoscaling:DescribeScalingProcessTypes'
                                - 'autoscaling:DescribeTerminationPolicyTypes'
                                - 'dynamodb:ListTables'
                                - 'autoscaling:DescribePolicies'
                                - 'ec2:DescribeInstanceAttribute'
                                - 'autoscaling:DescribeLaunchConfigurations'
                                - 'autoscaling:DescribeAdjustmentTypes'
                                - 'ec2:DescribeNetworkInterfaces'
                                - 'autoscaling:DescribeScalingActivities'
                                - 'autoscaling:DescribeAccountLimits'
                                - 'autoscaling:DescribeAutoScalingGroups'
                                - 'autoscaling:DescribeScheduledActions'
                                - 'autoscaling:DescribeLoadBalancerTargetGroups'
                                - 'autoscaling:DescribeNotificationConfigurations'
                                - 'autoscaling:DescribeLifecycleHookTypes'
                                - 'ec2:DetachNetworkInterface'
                                - 'autoscaling:DescribeTags'
                                - 'ec2:DeleteNetworkInterface'
                                - 'autoscaling:DescribeMetricCollectionTypes'
                                - 'autoscaling:DescribeLoadBalancers'
                                - 'autoscaling:DescribeLifecycleHooks'
                                - 'ec2:CreateNetworkInterface'
                                - 'ec2:ModifyNetworkInterfaceAttribute'
                                - 'ec2:ModifyInstanceAttribute'
                                - 'ec2:DescribeVpcs'
                                - 'ec2:AttachNetworkInterface'
                                - 'ec2:DescribeNetworkInterfaces'
                                - 'ec2:CreateTags'
                                - 'ec2:DeleteTags'
                                - 'ec2:DescribeVpcs'
                                - 'ec2:DescribeSubnets'
                            Resource: '*'
                          - Effect: Allow
                            Action:
                                - 'apigateway:GET'
                            Resource: !Sub
                                - 'arn:aws:apigateway:${AWS_REGION}::*'
                                - AWS_REGION: !Ref 'AWS::Region'
                          - Effect: Allow
                            Action:
                                - 's3:GetObject'
                                - 's3:ListBucket'
                            Resource: !If
                                - IfUseCustomAssetContainer
                                - - !Sub
                                    - >-
                                        arn:aws:s3:::${bucketname}/${keyprefix}assets/configset/*
                                    - bucketname: !Ref S3BucketName
                                      keyprefix: !Ref S3KeyPrefix
                                  - !Sub
                                    - 'arn:aws:s3:::${customContainer}/${customDirectory}/*'
                                    - customContainer: !Ref CustomAssetContainer
                                      customDirectory: !Ref CustomAssetDirectory
                                - - !Sub
                                    - >-
                                        arn:aws:s3:::${bucketname}/${keyprefix}assets/configset/*
                                    - bucketname: !Ref S3BucketName
                                      keyprefix: !Ref S3KeyPrefix
                          - Effect: Allow
                            Action:
                                - 'ec2:DisassociateTransitGatewayRouteTable'
                                - 'ec2:ModifyTransitGatewayVpcAttachment'
                                - 'ec2:DisableTransitGatewayRouteTablePropagation'
                                - 'ec2:CreateTransitGatewayRouteTable'
                                - 'ec2:AcceptTransitGatewayVpcAttachment'
                                - 'ec2:ReplaceTransitGatewayRoute'
                                - 'ec2:DeleteTransitGatewayRouteTable'
                                - 'ec2:CreateTransitGatewayRoute'
                                - 'ec2:DeleteTransitGatewayRoute'
                                - 'ec2:CreateTransitGatewayVpcAttachment'
                                - 'ec2:DeleteTransitGatewayVpcAttachment'
                                - 'ec2:AssociateTransitGatewayRouteTable'
                                - 'ec2:RejectTransitGatewayVpcAttachment'
                                - 'ec2:EnableTransitGatewayRouteTablePropagation'
                            Resource:
                                - !Sub
                                  - >-
                                      arn:aws:ec2:${AWS_REGION}:${AWS_ACCOUNT_ID}:transit-gateway-route-table/*
                                  - AWS_REGION: !Ref 'AWS::Region'
                                    AWS_ACCOUNT_ID: !Ref 'AWS::AccountId'
                                - !Sub
                                  - 'arn:aws:ec2:${AWS_REGION}:${AWS_ACCOUNT_ID}:vpc/*'
                                  - AWS_REGION: !Ref 'AWS::Region'
                                    AWS_ACCOUNT_ID: !Ref 'AWS::AccountId'
                                - !Sub
                                  - >-
                                      arn:aws:ec2:${AWS_REGION}:${AWS_ACCOUNT_ID}:transit-gateway/*
                                  - AWS_REGION: !Ref 'AWS::Region'
                                    AWS_ACCOUNT_ID: !Ref 'AWS::AccountId'
                                - !Sub
                                  - >-
                                      arn:aws:ec2:${AWS_REGION}:${AWS_ACCOUNT_ID}:transit-gateway-attachment/*
                                  - AWS_REGION: !Ref 'AWS::Region'
                                    AWS_ACCOUNT_ID: !Ref 'AWS::AccountId'
                          - Effect: Allow
                            Action:
                                - 'ec2:ExportTransitGatewayRoutes'
                                - 'ec2:DescribeVpnConnections'
                                - 'ec2:GetTransitGatewayAttachmentPropagations'
                                - 'ec2:DescribeTransitGateways'
                                - 'ec2:CreateCustomerGateway'
                                - 'ec2:DescribeCustomerGateways'
                                - 'ec2:SearchTransitGatewayRoutes'
                                - 'ec2:DescribeTransitGatewayAttachments'
                                - 'ec2:DescribeTransitGatewayRouteTables'
                                - 'ec2:GetTransitGatewayRouteTablePropagations'
                                - 'ec2:DescribeTransitGatewayVpcAttachments'
                                - 'ec2:DeleteVpnConnection'
                                - 'ec2:GetTransitGatewayRouteTableAssociations'
                                - 'ec2:CreateVpnConnection'
                            Resource: '*'
                          - Effect: Allow
                            Action: 'ec2:DeleteCustomerGateway'
                            Resource: !Sub
                                - >-
                                    arn:aws:ec2:${AWS_REGION}:${AWS_ACCOUNT_ID}:customer-gateway/*
                                - AWS_REGION: !Ref 'AWS::Region'
                                  AWS_ACCOUNT_ID: !Ref 'AWS::AccountId'
                          - Effect: Allow
                            Action:
                                - 'lambda:InvokeFunction'
                                - 'lambda:InvokeAsync'
                            Resource: !Sub
                                - >-
                                    arn:aws:lambda:${AWS_REGION}:${AWS_ACCOUNT_ID}:function:${CUSTOM_ID}-${UNIQUE_ID}*
                                - AWS_REGION: !Ref 'AWS::Region'
                                  AWS_ACCOUNT_ID: !Ref 'AWS::AccountId'
                                  CUSTOM_ID: !Ref CustomIdentifier
                                  UNIQUE_ID: !Ref UniqueId
Outputs:
    HandlerArn:
        Description: Transit Gateway VPN management handler function ARN
        Value: !GetAtt
            - TransitGatewayVpnHandler
            - Arn
    HandlerName:
        Description: Transit Gateway VPN management handler function Name
        Value: !Join
            - '-'
            - - !Ref CustomIdentifier
              - !Ref UniqueId
              - fortigate-transit-gateway-vpn-handler
